### ISSUE TITLE
Request: reconciliate log output and sentry event id

### ISSUE THREAD

**Issue by greut** [exoscale/reporter#17]
It would be super lovely to have the Sentry Event ID into the logs.

**now**

> {"@timestamp":"2018-05-23T16:42:45.090+02:00","@version":1,"message":"captured exception","logger_name":"spootnik.reporter",

**proposed**

> "message", "captured exception (eventid: 7b1fbbc69a3b40398676ac59920d7a06)", ...

So taking that a doing a search in sentry brings us to the right place.

https://sentry.internal.exoscale.ch/exoscale/api-gateway/issues/796/events/77430/

Thanks!

**Comment by chrisglass** [comment]
This can be done once https://github.com/exoscale/raven/pull/20 is merged (and a new release exists).

I have the reporter branch ready as well for reporter itself here: https://github.com/exoscale/reporter/pull/18

**Comment by greut** [comment]
done I guess.

**Comment by chrisglass** [comment]
Well, it would need a new release of reporter I guess, but yeah, the code is landed.
