### ISSUE TITLE
Add support for Integrant

### ISSUE THREAD

**Issue by giorgio-v** [exoscale/reporter#27]
Hi,
I’d like to float the idea of adding [Integrant](https://github.com/weavejester/integrant) support to this project. It seems like a nice addition to me, but of course I’d like to know your thoughts on this. 

Details are a bit fuzzy at this moment and I can provide them if you think the idea has any merit.

Please let me know. :)

**Comment by pyr** [comment]
We initially started with reporter as a component, but quickly realized we would rather have it run out of band from other components, much closer in spirit to what most people do with logging.

One of the future directions reporter might take would rather be to expose simple `start` and `stop` signatures, dissociated from *component*, and let those who would rather have it run within their DI solution of choice wire that in through `start` and `stop`, would this make sense?

**Comment by giorgio-v** [comment]
Yeah, in a way it is something I thought about. Even assuming it would be a good thing to add support for Integrant directly here, it would make only logical sense to decouple both DI-specific parts in, say, dedicated namespaces. The end result, seems to me, could be pretty similar to your description, where you leverage the `start` and `stop` you mentioned from those namespaces. 

Am I completely off track? 😅

**Comment by pyr** [comment]
Nope, I think we are saying essentially the same thing here.

**Comment by giorgio-v** [comment]
Would it be ok for you if I go ahead and create a pull request to discuss the thing more concretely?
